name: Docker Image CI
env:
  # image name, you need change this name if you copy it
  IMAGE_NAME: gray-test

on:
  push:
    tags:
      - '*'

jobs:
  build-docker-image:
    runs-on: ubuntu-20.04
    env:
      TZ: Asia/Shanghai
    steps:
      # checkout code
      - uses: actions/checkout@v2

      # login to docker hub
      - name: docker login
        env:
          DOCKER_UESR: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}
        run: |
          docker login -u $DOCKER_UESR -p $DOCKER_PASSWORD

      # build docker image
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USER }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
      
      # push image to hub
      - name: Docker push
        run: docker push ${{ secrets.DOCKER_USER }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
